apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: billsManager-dev
  name: billsManager
  labels:
    app: billsManager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billsManager
  template:
    metadata:
      labels:
        app: billsManager
    spec:
      containers:
      - name: billsManager
        env:
          - name: DB_HOST
            value: 127.0.0.1
          - name: DB_DATABASE
            value: billsManagerAdmin
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: connect
          - name: DB_PORT
            value: "31226"
        image: 127.0.0.1:8843/billsManager:2021.03.28.17.31.12
        ports:
        - containerPort: 7000
      imagePullSecrets:
        - name: regcred
