apiVersion: v1
kind: Service
metadata:
  namespace: billsManager-dev
  name: billsManager
  labels:
    app: billsManager
spec:
  type: NodePort
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: http
  selector:
    app: billsManager