apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31226
    protocol: TCP
    name: postgres
  selector:
    app: postgres